# Generated by Django 4.1.5 on 2023-05-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=20, unique=True)),
                ('courseCode', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('academicYear', models.CharField(max_length=10)),
                ('courseTitle', models.CharField(max_length=100)),
                ('numberOfStudent', models.PositiveIntegerField(default=0)),
                ('dropOrWithdraw', models.PositiveIntegerField(default=0)),
                ('failRate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teachingQualityScore', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('studentSatisfactionScore', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekFeedback', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='IEFF.courses')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SystemUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='professor', max_length=100)),
                ('drive_link', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewersFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirteriaStatus', models.TextField(blank=True, null=True)),
                ('Rationale', models.TextField(blank=True, null=True)),
                ('otherComments', models.TextField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers_feedback', to='IEFF.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueDescription', models.CharField(max_length=300)),
                ('improvementPlan', models.TextField(blank=True, null=True)),
                ('successIndicator', models.TextField(blank=True, null=True)),
                ('actualOutcome', models.TextField(blank=True, null=True)),
                ('endOfSemesterOutcome', models.TextField(blank=True, null=True)),
                ('actionsNeeded', models.TextField(blank=True, null=True)),
                ('reviewersFeedback', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='IEFF.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='IEFF.systemusers'),
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloId', models.CharField(max_length=20, unique=True)),
                ('cloMarks', models.PositiveIntegerField()),
                ('cloWeight', models.PositiveIntegerField()),
                ('achievementStatus', models.CharField(max_length=10)),
                ('assessment', models.TextField()),
                ('facultyComment', models.TextField()),
                ('reviewerComment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='IEFF.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeDescription', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='challenges', to='IEFF.courses')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentDescription', models.CharField(max_length=100)),
                ('clos', models.ManyToManyField(related_name='assessment_components', to='IEFF.clo')),
            ],
        ),
    ]
