# Generated by Django 4.1.5 on 2023-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0002_remove_clo_cloid_remove_courses_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='achievementStatus',
            field=models.CharField(choices=[('A', 'Achieved'), ('P', 'Partially Achieved'), ('NA', 'Not Achieved')], max_length=2),
        ),
    ]
