# Generated by Django 4.1.5 on 2023-05-09 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IEFF', '0004_alter_clo_achievementstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SystemUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
