# Generated by Django 4.1.5 on 2023-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0005_alter_systemusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusers',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('reviewer', 'Reviewer')], default=None, max_length=100),
        ),
    ]
