# Generated by Django 4.1.5 on 2023-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0008_remove_assessmentcomponent_assessmentdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='assessmentType',
            field=models.CharField(blank=True, choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Presentation', 'Presentation'), ('Midterm Exam', 'Midterm Exam'), ('Final Exam', 'Final Exam'), ('Project', 'Project'), ('Lab Report', 'Lab Report'), ('Essay', 'Essay'), ('Group Work', 'Group Work'), ('Research Paper', 'Research Paper'), ('Online Discussion', 'Online Discussion'), ('Peer Review', 'Peer Review'), ('Portfolio', 'Portfolio'), ('Case Study', 'Case Study'), ('Oral Examination', 'Oral Examination'), ('Practical Exam', 'Practical Exam'), ('Simulation', 'Simulation'), ('Field Work', 'Field Work'), ('Attendance', 'Attendance'), ('Participation', 'Participation')], max_length=20, null=True),
        ),
    ]
