# Generated by Django 4.1.5 on 2023-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0009_alter_assessmentcomponent_assessmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='cloMarks',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cloWeight',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
