# Generated by Django 4.1.5 on 2023-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0010_alter_clo_clomarks_alter_clo_cloweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='academicYear',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030')], max_length=10),
        ),
    ]
