# Generated by Django 4.1.5 on 2023-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0011_alter_courses_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=10),
        ),
    ]
