# Generated by Django 4.1.5 on 2023-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0012_alter_courses_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='achievementStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cloMarks',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cloWeight',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='facultyComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='reviewerComment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
