# Generated by Django 4.1.5 on 2023-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0013_alter_clo_achievementstatus_alter_clo_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cloMarks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cloWeight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
