# Generated by Django 4.1.5 on 2023-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0014_clo_index_alter_clo_clomarks_alter_clo_cloweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
