# Generated by Django 4.1.5 on 2023-06-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0015_week_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='index',
            new_name='weekIndex',
        ),
    ]
