# Generated by Django 4.1.5 on 2023-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0016_rename_index_week_weekindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='IssueIndex',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
