# Generated by Django 4.1.5 on 2023-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0017_issues_issueindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
