# Generated by Django 4.1.5 on 2023-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0018_challenges_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='courses',
        ),
        migrations.AddField(
            model_name='challenges',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='IEFF.courses'),
        ),
    ]
