# Generated by Django 4.1.5 on 2023-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0022_remove_slo_assessment_slo_assessment_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
