# Generated by Django 4.1.5 on 2023-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0023_slo_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slo',
            name='assessment_components',
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='slos',
            field=models.ManyToManyField(related_name='assessment_components', to='IEFF.slo'),
        ),
    ]
