# Generated by Django 4.1.5 on 2023-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0024_remove_slo_assessment_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='sloId',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
