# Generated by Django 4.1.5 on 2023-07-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0025_slo_sloid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slo',
            name='sloId',
        ),
    ]
