# Generated by Django 4.1.5 on 2023-07-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0026_remove_slo_sloid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcomponent',
            name='slos',
        ),
        migrations.AddField(
            model_name='slo',
            name='assessment_components',
            field=models.ManyToManyField(related_name='slos', to='IEFF.assessmentcomponent'),
        ),
    ]
