# Generated by Django 4.1.5 on 2023-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEFF', '0028_remove_slo_assessment_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='assessments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
